### ISSUE TITLE
LICENSE file request

### ISSUE THREAD

**Issue by arcturusannamalai** [AshokR/TamilNLP#2]
Ashok and team: Can you please add a LICENSE file or COPYING file describing the Apache license you are intending to use?

Best Regards,
-Muthu

**Comment by AshokR** [comment]
Thanks for looking into these. I have linked to the Apache 2.0 license in the Readme.md file. Hope that will work.

**Comment by arcturusannamalai** [comment]
Thanks, Ashok!
