### ISSUE TITLE
want for python 3

### ISSUE THREAD

**Issue by anandaveeryan** [AshokR/TamilNLP#6]
please we want it for python 3

**Comment by AshokR** [comment]
I am not a professional coder. I only do a little bit of hacking. My suggestions are:
1. You can try and port the code to Python 3 and send a pull request or
2. Say which code is priority for you and what you are trying to accomplish and someone else may be able to help.
Good luck!

**Comment by anandaveeryan** [comment]
Thanks.
Can you please suggest me the path to start learning hacking

**Comment by AshokR** [comment]
Please say what you are trying to accomplish if the code is available for Python 3. This will help me, and others, to recommend the best way for you to reach that goal.
